### ISSUE TITLE
placeholder is falsy or truthy only

### ISSUE THREAD

**Issue by nmccready** [jasonslyvia/react-lazyload#86]
[Current code](https://github.com/jasonslyvia/react-lazyload/blob/master/src/index.jsx#L267-L270) only allows overriding the placeholder or getting the default.

It would be nice to either allow `null` to represent two possibilities:
- no placeholder
- a placeholder with no `height` or `display:none`

Another alternative would be to allow for another props of placeholderHeight.

I am not sure how this should go; but I thought I would bring it up.

**Comment by jasonslyvia** [comment]
Actually there has to be a 'placeholder' with `height` larger than zero (ideally matching the rendered component) , in order to properly calculate whether a lazy loaded component is visible or not.

Just imagine a document populated with lazy loaded components which has no placeholder with `height`, LazyLoad will just render them all because when it comes to calculating, all components is visible in viewport, that will make lazy load meaningless.

**Comment by jasonslyvia** [comment]
I'm closing this issue for now, but feel free to reopen it if there is some other concerns.
